export const CATEGORIES_ACTION_TYPES = {
  FETCH_CATEGORIES_START: "categories/FETCH_CATEGORIES_START",
  FETCH_CATEGORIES_SUCCEED: "categories/FETCH_CATEGORIES_SUCCEED",
  FETCH_CATEGORIES_FAILED: "categories/FETCH_CATEGORIES_FAILED",
};
